import random
import asyncio
import time

thinking_messages = [
  "Fetching data...",
  "I'm thinking...",
  "Still thinking...",
  "Analyzing data...",
  "Getting snacks...",
  "Reticulating splines...",
  "Generating witty dialog...",
  "Swapping time and space...",
  "Spinning violently around the y-axis...",
  "Tokenizing real life...",
  "Bending the spoon...",
  "Filtering morale...",
  "Gathering purple hippos...",
  "We need a new fuse...",
  "640K ought to be enough for anybody",
  "The architects are still drafting...",
  "Breeding some more bits...",
  "Waiting for the elves to clock in...",
  "Testing patience...",
  "Encouraging the penguins...",
  "Sharpening the knives...",
  "Answering questions...",
  "Reconfoobling energymotron...",
  "It's not you. It's me.",
  "Counting backwards from Infinity...",
  "Don't panic...",
  "Embiggening Prototypes...",
  "Creating time-loop inversion field...",
  "Spinning the wheel of fortune...",
  "Loading the enchanted bunny...",
  "Computing chance of success...",
  "Looking for exact change...",
  "Pulling out my checkbook...",
  "I feel like im supposed to be loading something...",
  "Getting back on track...",
  "Should have used a compiled language...",
  "Adjusting flux capacitor...",
  "Shoving sloths...",
  "I swear it's almost done.",
  "Let's take a mindfulness minute...",
  "Listening for the sound of one hand clapping...",
  "Keeping all the 1's and removing all the 0's...",
  "Putting the icing on the cake. The cake is not a lie...",
  "Cleaning off the cobwebs...",
  "Making sure all the i's have dots...",
  "Aligning dilithium crystals...",
  "Connecting Neurotoxin Storage Tank...",
  "Granting wishes...",
  "Spinning the hamster…",
  "99 bottles of beer on the wall...",
  "Stay awhile and listen...",
  "Convincing AI not to turn evil...",
  "What's that smell?",
  "Constructing additional pylons...",
  "Roping some seaturtles...",
  "Locating Jebediah Kerman...",
  "We are not liable for any broken screens as a result of waiting.",
  "turning it off and on again...",
  "Well, this is embarrassing.",
  "Whoops...",
  "Shhh....",
  "Didn't know paint dried so quickly.",
  "Walking several dogs...",
  "Organizing socks...",
  "Dividing by zero...",
  "Consulting chuck norris...",
  "Cracking military-grade encryption...",
  "Simulating traveling salesman...",
  "Proving P=NP...",
  "Entangling superstrings...",
  "Twiddling thumbs...",
  "Searching for plot device...",
  "Trying to sort in O(n)...",
  "Searching for more jokes...",
  "Waiting for the intern to get more coffee...",
  "convert this bug to a feature...",
  "Winter is coming...",
  "Updating dependencies...",
  "Installing dependencies...",
  "Uninstalling dependencies...",
  "Switching to the latest COBOL framework...",
  "Distracted by cat gifs...",
  "Finding someone to hold my beer...",
  "Aw, snap! Not..",
  "Ordering 1s and 0s...",
  "Consulting the manual...",
  "Feel free to spin in your chair",
  "Downloading more RAM...",
  "Mining some bitcoins...",
  "Downloading more RAM..",
  "Updating to Windows Vista...",
  "Deleting something...",
  "Initializing the initializer...",
  "Finishing the finisher...",
  "Optimizing the optimizer...",
  "Compiling the compiler...",
  "Updating Updater...",
  "Downloading Downloader...",
  "Debugging Debugger...",
  "Awaiting the awaiter...",
  "Googling it...",
  "Shovelling coal into the server...",
  "Pushing pixels...",
  "Building a wall...",
  "Reading Terms and Conditions for you...",
  "Running with scissors...",
  "Definitely not a virus...",
  "Work, work...",
  "Discovering new ways of making you wait...",
  "Your time is very important to us...",
  "Catching em' all...",
  "Finding elevator music...",
  "Grabbing extra minions...",
  "Warming up...",
  "Starting over...",
  "Resetting the machine...",
  "Doing the heavy lifting...",
  "We're working very Hard .... Really",
  "Waking up the minions",
  "Serve other customers...",
  "Our premium plan is faster",
  "Feeding unicorns...",
  "Rupturing the subspace barrier...",
  "Creating an anti-time reaction...",
  "Converging tachyon pulses...",
  "Bypassing control of the matter-antimatter integrator...",
  "Adjusting the dilithium crystal converter assembly...",
  "Reversing the shield polarity...",
  "Disrupting warp fields with an inverse graviton burst..."
]

async def thinking(ctx, seconds = 60, duration = 2):
  msg = await ctx.send('let me think...')
  for i in range(round(seconds / duration)):
    try:
      newMsg = random.choice(thinking_messages)
      await asyncio.sleep(duration)
      await msg.edit(content=newMsg)
    except asyncio.CancelledError:
      await msg.delete()
      return msg

  await msg.delete()
  return msg
