//! The 200 emoji Jev picks reactions from ([`crate::jev::reaction`]).
//!
//! Roughly the most-used emoji by global frequency (Unicode's emoji frequency
//! data), lightly nudged toward what a gaming Discord actually reacts with — a few
//! symbols nobody reacts with were swapped for 🎮, 🍿, 🫡 and friends. Ordered
//! most to least used, as `(name, emoji)`. The name is the option id Jev sees next
//! to the glyph, so it doubles as a description; keep them unique.
//!
//! The array length is part of the type, so adding or dropping one without
//! swapping another in won't compile. Jev's Choice tops out at 255 options.

pub const TOP_EMOJI: [(&str, &str); 200] = [
    ("face_with_tears_of_joy", "😂"),
    ("red_heart", "❤️"),
    ("rolling_on_the_floor_laughing", "🤣"),
    ("thumbs_up", "👍"),
    ("loudly_crying_face", "😭"),
    ("folded_hands", "🙏"),
    ("face_blowing_a_kiss", "😘"),
    ("smiling_face_with_hearts", "🥰"),
    ("smiling_face_with_heart_eyes", "😍"),
    ("smiling_face_with_smiling_eyes", "😊"),
    ("party_popper", "🎉"),
    ("beaming_face_with_smiling_eyes", "😁"),
    ("two_hearts", "💕"),
    ("pleading_face", "🥺"),
    ("grinning_face_with_sweat", "😅"),
    ("fire", "🔥"),
    ("smiling_face", "☺️"),
    ("person_facepalming", "🤦"),
    ("heart_suit", "♥️"),
    ("person_shrugging", "🤷"),
    ("face_with_rolling_eyes", "🙄"),
    ("grinning_squinting_face", "😆"),
    ("hugging_face", "🤗"),
    ("winking_face", "😉"),
    ("birthday_cake", "🎂"),
    ("thinking_face", "🤔"),
    ("clapping_hands", "👏"),
    ("slightly_smiling_face", "🙂"),
    ("flushed_face", "😳"),
    ("partying_face", "🥳"),
    ("smiling_face_with_sunglasses", "😎"),
    ("ok_hand", "👌"),
    ("purple_heart", "💜"),
    ("pensive_face", "😔"),
    ("flexed_biceps", "💪"),
    ("sparkles", "✨"),
    ("sparkling_heart", "💖"),
    ("eyes", "👀"),
    ("face_savoring_food", "😋"),
    ("smirking_face", "😏"),
    ("crying_face", "😢"),
    ("backhand_index_pointing_right", "👉"),
    ("growing_heart", "💗"),
    ("weary_face", "😩"),
    ("hundred_points", "💯"),
    ("rose", "🌹"),
    ("revolving_hearts", "💞"),
    ("balloon", "🎈"),
    ("blue_heart", "💙"),
    ("grinning_face_with_big_eyes", "😃"),
    ("enraged_face", "😡"),
    ("bouquet", "💐"),
    ("winking_face_with_tongue", "😜"),
    ("see_no_evil_monkey", "🙈"),
    ("crossed_fingers", "🤞"),
    ("grinning_face_with_smiling_eyes", "😄"),
    ("drooling_face", "🤤"),
    ("raising_hands", "🙌"),
    ("zany_face", "🤪"),
    ("heart_exclamation", "❣️"),
    ("grinning_face", "😀"),
    ("kiss_mark", "💋"),
    ("skull", "💀"),
    ("backhand_index_pointing_down", "👇"),
    ("broken_heart", "💔"),
    ("relieved_face", "😌"),
    ("beating_heart", "💓"),
    ("star_struck", "🤩"),
    ("upside_down_face", "🙃"),
    ("grimacing_face", "😬"),
    ("face_screaming_in_fear", "😱"),
    ("sleeping_face", "😴"),
    ("face_with_hand_over_mouth", "🤭"),
    ("neutral_face", "😐"),
    ("sun_with_face", "🌞"),
    ("unamused_face", "😒"),
    ("smiling_face_with_halo", "😇"),
    ("cherry_blossom", "🌸"),
    ("smiling_face_with_horns", "😈"),
    ("musical_notes", "🎶"),
    ("victory_hand", "✌️"),
    ("confetti_ball", "🎊"),
    ("hot_face", "🥵"),
    ("disappointed_face", "😞"),
    ("green_heart", "💚"),
    ("sun", "☀️"),
    ("black_heart", "🖤"),
    ("money_bag", "💰"),
    ("kissing_face_with_closed_eyes", "😚"),
    ("crown", "👑"),
    ("wrapped_gift", "🎁"),
    ("collision", "💥"),
    ("person_raising_hand", "🙋"),
    ("frowning_face", "☹️"),
    ("expressionless_face", "😑"),
    ("woozy_face", "🥴"),
    ("backhand_index_pointing_left", "👈"),
    ("pile_of_poo", "💩"),
    ("check_mark_button", "✅"),
    ("waving_hand", "👋"),
    ("face_vomiting", "🤮"),
    ("face_with_steam_from_nose", "😤"),
    ("nauseated_face", "🤢"),
    ("glowing_star", "🌟"),
    ("red_exclamation_mark", "❗"),
    ("sad_but_relieved_face", "😥"),
    ("rainbow", "🌈"),
    ("yellow_heart", "💛"),
    ("squinting_face_with_tongue", "😝"),
    ("tired_face", "😫"),
    ("astonished_face", "😲"),
    ("middle_finger", "🖕"),
    ("double_exclamation_mark", "‼️"),
    ("robot", "🤖"),
    ("sunflower", "🌻"),
    ("exploding_head", "🤯"),
    ("woman_dancing", "💃"),
    ("oncoming_fist", "👊"),
    ("face_with_symbols_on_mouth", "🤬"),
    ("money_with_wings", "💸"),
    ("confused_face", "😕"),
    ("eye", "👁️"),
    ("high_voltage", "⚡"),
    ("hot_beverage", "☕"),
    ("four_leaf_clover", "🍀"),
    ("sweat_droplets", "💦"),
    ("star", "⭐"),
    ("butterfly", "🦋"),
    ("face_with_raised_eyebrow", "🤨"),
    ("hibiscus", "🌺"),
    ("cat_with_tears_of_joy", "😹"),
    ("sign_of_the_horns", "🤘"),
    ("tulip", "🌷"),
    ("heart_with_ribbon", "💝"),
    ("zzz", "💤"),
    ("handshake", "🤝"),
    ("rabbit_face", "🐰"),
    ("downcast_face_with_sweat", "😓"),
    ("heart_with_arrow", "💘"),
    ("clinking_beer_mugs", "🍻"),
    ("worried_face", "😟"),
    ("persevering_face", "😣"),
    ("face_with_monocle", "🧐"),
    ("angry_face", "😠"),
    ("cowboy_hat_face", "🤠"),
    ("smiling_cat_with_heart_eyes", "😻"),
    ("crescent_moon", "🌙"),
    ("face_with_tongue", "😛"),
    ("call_me_hand", "🤙"),
    ("speak_no_evil_monkey", "🙊"),
    ("orange_heart", "🧡"),
    ("clown_face", "🤡"),
    ("shushing_face", "🤫"),
    ("blossom", "🌼"),
    ("clinking_glasses", "🥂"),
    ("face_with_medical_mask", "😷"),
    ("nerd_face", "🤓"),
    ("cold_face", "🥶"),
    ("face_without_mouth", "😶"),
    ("confounded_face", "😖"),
    ("musical_note", "🎵"),
    ("heart_hands", "🫶"),
    ("kissing_face_with_smiling_eyes", "😙"),
    ("eggplant", "🍆"),
    ("money_mouth_face", "🤑"),
    ("nail_polish", "💅"),
    ("kissing_face", "😗"),
    ("dog_face", "🐶"),
    ("strawberry", "🍓"),
    ("tongue", "👅"),
    ("mouth", "👄"),
    ("herb", "🌿"),
    ("police_car_light", "🚨"),
    ("video_game", "🎮"),
    ("popcorn", "🍿"),
    ("leaf_fluttering_in_wind", "🍃"),
    ("face_with_open_mouth", "😮"),
    ("sneezing_face", "🤧"),
    ("water_wave", "🌊"),
    ("backhand_index_pointing_up", "👆"),
    ("peach", "🍑"),
    ("wine_glass", "🍷"),
    ("slightly_frowning_face", "🙁"),
    ("cross_mark", "❌"),
    ("check_mark", "✔️"),
    ("microphone", "🎤"),
    ("cat_face", "🐱"),
    ("pizza", "🍕"),
    ("beer_mug", "🍺"),
    ("soccer_ball", "⚽"),
    ("trophy", "🏆"),
    ("rocket", "🚀"),
    ("goat", "🐐"),
    ("brain", "🧠"),
    ("saluting_face", "🫡"),
    ("melting_face", "🫠"),
    ("sleepy_face", "😪"),
    ("thumbs_down", "👎"),
    ("pinched_fingers", "🤌"),
    ("crab", "🦀"),
];

#[cfg(test)]
mod tests {
    use super::TOP_EMOJI;
    use std::collections::HashSet;

    #[test]
    fn names_and_emoji_are_unique() {
        let names: HashSet<_> = TOP_EMOJI.iter().map(|(n, _)| n).collect();
        let glyphs: HashSet<_> = TOP_EMOJI.iter().map(|(_, e)| e).collect();
        assert_eq!(names.len(), TOP_EMOJI.len());
        assert_eq!(glyphs.len(), TOP_EMOJI.len());
    }
}
